name: Docker Image CI

on:
  push:
    paths:
      - "testchart/Chart.yaml"
    branches: [ "develop" ]


jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Read appVersion from Chart.yaml
      id: read_version
      run: echo "::set-output name=app_version::$(grep 'appVersion' testchart/Chart.yaml | cut -d '"' -f 2)"

    - name: Replace appVersion in index.html
      run: echo "${{ steps.read_version.outputs.app_version }}" > index.html

    - name: Commit change
      run: |
        git config --global user.name 'editBot'
        git config --global user.email 'actions@users.noreply.github.com'
        git add index.html
        git commit -m "Update appVersion in index.html"
        git tag -a "v${{ steps.read_version.outputs.app_version }}" -m "Version v${{ steps.read_version.outputs.app_version }}"

    - name: Push changes and tag
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: develop
        tags: 'v${{ steps.read_version.outputs.app_version }}'

    - name: Build Docker image
      run: docker build -t testNginx .

    - name: Tag Docker image
      run: docker tag testNginx ${{ secrets.NCR_URL }}/nginx:${{ steps.read_version.outputs.app_version }}

    - name: Login to Private Docker registry
      run: docker login -u ${{ secrets.NCR_ACCESS_KEY }} -p ${{ secrets.NCR_NCR_SECRET_KEY }} ${{ secrets.NCR_URL }}

    - name: Push Docker image
      run: docker push ${{ secrets.NCR_URL }}/cd-jenkins/nginx:${{ steps.read_version.outputs.app_version }}
